#Amir El khargui, COP2500
#Vehicle.py - This program draws my ideal vehicle for roaming the knightrola region

import turtle

my_screen = turtle.getscreen()
my_turtle = turtle.Turtle()

#Colors 
my_turtle.pencolor("black")
my_turtle.pensize(7)
my_turtle.fillcolor("red")
my_turtle.begin_fill()
#Drawing for ideal vehicle
my_turtle.forward(300)
my_turtle.circle(-40)
my_turtle.backward(300)
my_turtle.circle(-40)
my_turtle.left(90)
my_turtle.forward(2)
my_turtle.left(90)
my_turtle.circle(50, 90)
my_turtle.right(90)
my_turtle.forward(200)
my_turtle.right(90)
my_turtle.forward(300)
my_turtle.right(90)
my_turtle.forward(200)
my_turtle.right(90)
my_turtle.forward(30)
my_turtle.left(90)
my_turtle.forward(300)
my_turtle.left(90)
my_turtle.forward(20)
my_turtle.right(90)
my_turtle.forward(10)
my_turtle.right(90)
my_turtle.forward(20)
my_turtle.left(90)
my_turtle.forward(30)
my_turtle.circle(-100, 90)
my_turtle.left(90)
my_turtle.forward(30)
my_turtle.circle(-50, 90)
my_turtle.forward(115)
my_turtle.right(90)
my_turtle.forward(120)
my_turtle.right(90)
my_turtle.circle(45, 90)
my_turtle.penup()
my_turtle.goto(10,100)
my_turtle.pendown()
my_turtle.circle(20,180)
my_turtle.forward(300)
my_turtle.circle(20,180)
my_turtle.forward(300)
my_turtle.penup()
my_turtle.goto(-50, 250)
my_turtle.pendown()
my_turtle.left(90)
my_turtle.forward(300)
my_turtle.penup()
my_turtle.goto(300,180)
my_turtle.pendown()
my_turtle.right(90)
my_turtle.circle(60,-90)
my_turtle.left(90)
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.forward(60)
my_turtle.right(90)
my_turtle.forward(40)
#fill color ending
my_turtle.end_fill()


